### ISSUE TITLE
[feat] todo 관련 나머지 함수들 타입 지정 마무리

### ISSUE THREAD

**Issue by meeyoungchoi-front-dev** [meeyoungchoi-front-dev/typescript#32]
- [x] todoItems의 타입을 더 구체적으로 지정 {id: number, title: string , done: boolean}[];
- [x] todo의 타입을 더 구체적으로 지정 {id:number, title: string, done: boolean}
- [x] showComplete 완료된 투두 목록에 대해서는 object[ ]을 반환하도록 타입 지정
- [x] addTwoTodoItmes에 item 객체를 만들어서 addTodo가 호출되도록 기능 개발

```
todoItems = fetchTodoItems();
addTwoTodoItems();
log();

```

스크린샷
![image](https://github.com/user-attachments/assets/27b471d9-44e1-4e51-ac8f-04bab74063fe)
